INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (268, 'ГРУЗИЯ', 'Грузия', 'Georgia, Republic of', 268, 'GE', 'GEO', 'GE', 'A');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (270, 'ГАМБИЯ', 'Республика Гамбия', 'Gambia', 270, 'GM', 'GMB', 'GM', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (275, 'ПАЛЕСТИНСКАЯ ТЕРРИТОРИЯ, ОККУПИРОВАННАЯ', 'Оккупированная Палестинская территория', 'Palestinian Territory', 275, 'PS', 'PSE', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (276, 'ГЕРМАНИЯ', 'Федеративная Республика Германия', 'Germany', 276, 'DE', 'DEU', 'DE', 'A');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (288, 'ГАНА', 'Республика Гана', 'Ghana', 288, 'GH', 'GHA', 'GH', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (292, 'ГИБРАЛТАР', '', 'Gibraltar', 292, 'GI', 'GIB', 'GI', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (296, 'КИРИБАТИ', 'Республика Кирибати', 'Kiribati', 296, 'KI', 'KIR', 'KI', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (300, 'ГРЕЦИЯ', 'Греческая Республика', 'Greece', 300, 'GR', 'GRC', 'GR', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (304, 'ГРЕНЛАНДИЯ', '', 'Greenland', 304, 'GL', 'GRL', 'GL', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (308, 'ГРЕНАДА', '', 'Grenada', 308, 'GD', 'GRD', 'GD', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (312, 'ГВАДЕЛУПА', '', 'Guadeloupe', 312, 'GP', 'GLP', 'GP', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (316, 'ГУАМ', '', 'Guam', 316, 'GU', 'GUM', 'GU', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (320, 'ГВАТЕМАЛА', 'Республика Гватемала', 'Guatemala', 320, 'GT', 'GTM', 'GT', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (324, 'ГВИНЕЯ', 'Гвинейская Республика', 'Guinea', 324, 'GN', 'GIN', 'GN', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (328, 'ГАЙАНА', 'Республика Гайана', 'Guyana', 328, 'GY', 'GUY', 'GY', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (332, 'ГАИТИ', 'Республика Гаити', 'Haiti', 332, 'HT', 'HTI', 'HT', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (334, 'ОСТРОВ ХЕРД И ОСТРОВА МАКДОНАЛЬД', '', 'Heard Island and McDonald Islands', 334, 'HM', 'HMD', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (336, 'ПАПСКИЙ ПРЕСТОЛ (ГОСУДАРСТВО - ГОРОД ВАТИКАН)', '', 'Vatican City', 336, 'VA', 'VAT', 'VA', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (340, 'ГОНДУРАС', 'Республика Гондурас', 'Honduras', 340, 'HN', 'HND', 'HN', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (344, 'ГОНКОНГ', 'Специальный административный регион Китая Гонконг', 'Hong Kong', 344, 'HK', 'HKG', 'HK', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (348, 'ВЕНГРИЯ', 'Венгерская Республика', 'Hungary', 348, 'HU', 'HUN', 'HU', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (352, 'ИСЛАНДИЯ', 'Республика Исландия', 'Iceland', 352, 'IS', 'ISL', 'IS', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (356, 'ИНДИЯ', 'Республика Индия', 'India', 356, 'IN', 'IND', 'IN', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (360, 'ИНДОНЕЗИЯ', 'Республика Индонезия', 'Indonesia', 360, 'ID', 'IDN', 'ID', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (364, 'ИРАН, ИСЛАМСКАЯ РЕСПУБЛИКА', 'Исламская Республика Иран', 'Iran', 364, 'IR', 'IRN', 'IR', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (368, 'ИРАК', 'Республика Ирак', 'Iraq', 368, 'IQ', 'IRQ', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (372, 'ИРЛАНДИЯ', '', 'Ireland', 372, 'IE', 'IRL', 'IE', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (376, 'ИЗРАИЛЬ', 'Государство Израиль', 'Israel', 376, 'IL', 'ISR', 'IL', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (380, 'ИТАЛИЯ', 'Итальянская Республика', 'Italy', 380, 'IT', 'ITA', 'IT', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (384, 'КОТ Д''ИВУАР', 'Республика Кот д''Ивуар', 'Cote D''Ivoire', 384, 'CI', 'CIV', 'CI', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (388, 'ЯМАЙКА', '', 'Jamaica', 388, 'JM', 'JAM', 'JM', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (392, 'ЯПОНИЯ', '', 'Japan', 392, 'JP', 'JPN', 'JP', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (398, 'КАЗАХСТАН', 'Республика Казахстан', 'Kazakhstan', 398, 'KZ', 'KAZ', 'KZ', 'A');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (400, 'ИОРДАНИЯ', 'Иорданское Хашимитское Королевство', 'Jordan', 400, 'JO', 'JOR', 'JO', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (404, 'КЕНИЯ', 'Республика Кения', 'Kenya', 404, 'KE', 'KEN', 'KE', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (408, 'КОРЕЯ, НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА', 'Корейская Народно-Демократическая Республика', 'Korean Democratic People''s Republic', 408, 'KP', 'PRK', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (410, 'КОРЕЯ, РЕСПУБЛИКА', 'Республика Корея', 'South Korea', 410, 'KR', 'KOR', 'KR', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (414, 'КУВЕЙТ', 'Государство Кувейт', 'Kuwait', 414, 'KW', 'KWT', 'KW', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (417, 'КИРГИЗИЯ', 'Киргизская Республика', 'Kyrgyzstan', 417, 'KG', 'KGZ', 'KG', 'A');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (418, 'ЛАОССКАЯ НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА', '', 'Laos', 418, 'LA', 'LAO', 'LA', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (422, 'ЛИВАН', 'Ливанская Республика', 'Lebanon', 422, 'LB', 'LBN', 'LB', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (426, 'ЛЕСОТО', 'Королевство Лесото', 'Lesotho', 426, 'LS', 'LSO', 'LS', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (428, 'ЛАТВИЯ', 'Латвийская Республика', 'Latvia', 428, 'LV', 'LVA', 'LV', 'A');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (430, 'ЛИБЕРИЯ', 'Республика Либерия', 'Liberia', 430, 'LR', 'LBR', 'LR', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (434, 'ЛИВИЙСКАЯ АРАБСКАЯ ДЖАМАХИРИЯ', 'Социалистическая Народная Ливийская Арабская Джамахирия', 'Libya', 434, 'LY', 'LBY', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (438, 'ЛИХТЕНШТЕЙН', 'Княжество Лихтенштейн', 'Liechtenstein', 438, 'LI', 'LIE', 'LI', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (440, 'ЛИТВА', 'Литовская Республика', 'Lithuania', 440, 'LT', 'LTU', 'LT', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (442, 'ЛЮКСЕМБУРГ', 'Великое Герцогство Люксембург', 'Luxembourg', 442, 'LU', 'LUX', 'LU', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (446, 'МАКАО', 'Специальный административный регион Китая Макао', 'Macau', 446, 'MO', 'MAC', 'MO', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (450, 'МАДАГАСКАР', 'Республика Мадагаскар', 'Madagascar', 450, 'MG', 'MDG', 'MG', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (454, 'МАЛАВИ', 'Республика Малави', 'Malawi', 454, 'MW', 'MWI', 'MW', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (458, 'МАЛАЙЗИЯ', '', 'Malaysia', 458, 'MY', 'MYS', 'MY', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (462, 'МАЛЬДИВЫ', 'Мальдивская Республика', 'Maldives', 462, 'MV', 'MDV', 'MV', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (466, 'МАЛИ', 'Республика Мали', 'Mali', 466, 'ML', 'MLI', 'ML', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (470, 'МАЛЬТА', 'Республика Мальта', 'Malta', 470, 'MT', 'MLT', 'MT', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (474, 'МАРТИНИКА', '', 'Martinique', 474, 'MQ', 'MTQ', 'MQ', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (478, 'МАВРИТАНИЯ', 'Исламская Республика Мавритания', 'Mauritania', 478, 'MR', 'MRT', 'MR', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (480, 'МАВРИКИЙ', 'Республика Маврикий', 'Mauritius', 480, 'MU', 'MUS', 'MU', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (484, 'МЕКСИКА', 'Мексиканские Соединенные Штаты', 'Mexico', 484, 'MX', 'MEX', 'MX', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (492, 'МОНАКО', 'Княжество Монако', 'Monaco', 492, 'MC', 'MCO', 'MC', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (496, 'МОНГОЛИЯ', '', 'Mongolia', 496, 'MN', 'MNG', 'MN', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (498, 'МОЛДОВА, РЕСПУБЛИКА', 'Республика Молдова', 'Moldova', 498, 'MD', 'MDA', 'MD', 'A');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (499, 'ЧЕРНОГОРИЯ', '', 'Montenegro', 499, 'ME', 'MNE', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (500, 'МОНТСЕРРАТ', '', 'Montserrat', 500, 'MS', 'MSR', 'MS', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (504, 'МАРОККО', 'Королевство Марокко', 'Morocco', 504, 'MA', 'MAR', 'MA', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (508, 'МОЗАМБИК', 'Республика Мозамбик', 'Mozambique', 508, 'MZ', 'MOZ', 'MZ', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (512, 'ОМАН', 'Султанат Оман', 'Oman', 512, 'OM', 'OMN', 'OM', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (516, 'НАМИБИЯ', 'Республика Намибия', 'Namibia', 516, 'NA', 'NAM', 'NA', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (520, 'НАУРУ', 'Республика Науру', 'Nauru', 520, 'NR', 'NRU', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (524, 'НЕПАЛ', 'Федеративная Демократическая Республика Непал', 'Nepal', 524, 'NP', 'NPL', 'NP', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (528, 'НИДЕРЛАНДЫ', 'Королевство Нидерландов', 'Netherlands', 528, 'NL', 'NLD', 'NL', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (531, 'КЮРАСАО', '', 'Curacao', 531, 'CW', 'CUW', 'CB', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (533, 'АРУБА', '', 'Aruba', 533, 'AW', 'ABW', 'AW', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (534, 'СЕН-МАРТЕН (нидерландская часть)', '', 'St. Martin', 534, 'SX', 'SXM', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (535, 'БОНЭЙР, СИНТ-ЭСТАТИУС И САБА', '', 'Bonaire, St. Eustatius and Saba (BES)', 535, 'BQ', 'BES', 'BL', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (540, 'НОВАЯ КАЛЕДОНИЯ', '', 'New Caledonia', 540, 'NC', 'NCL', 'NC', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (548, 'ВАНУАТУ', 'Республика Вануату', 'Vanuatu', 548, 'VU', 'VUT', 'VU', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (554, 'НОВАЯ ЗЕЛАНДИЯ', '', 'New Zealand', 554, 'NZ', 'NZL', 'NZ', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (558, 'НИКАРАГУА', 'Республика Никарагуа', 'Nicaragua', 558, 'NI', 'NIC', 'NI', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (562, 'НИГЕР', 'Республика Нигер', 'Niger', 562, 'NE', 'NER', 'NE', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (566, 'НИГЕРИЯ', 'Федеративная Республика Нигерия', 'Nigeria', 566, 'NG', 'NGA', 'NG', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (570, 'НИУЭ', 'Республика Ниуэ', 'Niue', 570, 'NU', 'NIU', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (574, 'ОСТРОВ НОРФОЛК', '', 'Norfolk Island', 574, 'NF', 'NFK', 'NF', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (578, 'НОРВЕГИЯ', 'Королевство Норвегия', 'Norway', 578, 'NO', 'NOR', 'NO', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (580, 'СЕВЕРНЫЕ МАРИАНСКИЕ ОСТРОВА', 'Содружество Северных Марианских островов', 'Saipan', 580, 'MP', 'MNP', 'MP', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (581, 'МАЛЫЕ ТИХООКЕАНСКИЕ ОТДАЛЕННЫЕ ОСТРОВА СОЕДИНЕННЫХ ШТАТОВ', '', 'United States Pacific Island Wildlife Refuges', 581, 'UM', 'UMI', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (583, 'МИКРОНЕЗИЯ, ФЕДЕРАТИВНЫЕ ШТАТЫ', 'Федеративные штаты Микронезии', 'Micronesia', 583, 'FM', 'FSM', 'FM', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (584, 'МАРШАЛЛОВЫ ОСТРОВА', 'Республика Маршалловы Острова', 'Marshall Islands', 584, 'MH', 'MHL', 'MH', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (585, 'ПАЛАУ', 'Республика Палау', 'Palau', 585, 'PW', 'PLW', 'PW', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (586, 'ПАКИСТАН', 'Исламская Республика Пакистан', 'Pakistan', 586, 'PK', 'PAK', 'PK', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (591, 'ПАНАМА', 'Республика Панама', 'Panama', 591, 'PA', 'PAN', 'PA', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (598, 'ПАПУА-НОВАЯ ГВИНЕЯ', '', 'Papua New Guinea', 598, 'PG', 'PNG', 'PG', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (600, 'ПАРАГВАЙ', 'Республика Парагвай', 'Paraguay', 600, 'PY', 'PRY', 'PY', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (604, 'ПЕРУ', 'Республика Перу', 'Peru', 604, 'PE', 'PER', 'PE', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (608, 'ФИЛИППИНЫ', 'Республика Филиппины', 'Philippines', 608, 'PH', 'PHL', 'PH', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (612, 'ПИТКЕРН', '', 'Pitcairn', 612, 'PN', 'PCN', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (616, 'ПОЛЬША', 'Республика Польша', 'Poland', 616, 'PL', 'POL', 'PL', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (620, 'ПОРТУГАЛИЯ', 'Португальская Республика', 'Portugal', 620, 'PT', 'PRT', 'PT', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (624, 'ГВИНЕЯ-БИСАУ', 'Республика Гвинея-Бисау', 'Guinea-Bissau', 624, 'GW', 'GNB', 'GW', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (626, 'ТИМОР-ЛЕСТЕ', 'Демократическая Республика Тимор-Лесте', 'Timor-Leste', 626, 'TL', 'TLS', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (630, 'ПУЭРТО-РИКО', '', 'Puerto Rico', 630, 'PR', 'PRI', 'PR', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (634, 'КАТАР', 'Государство Катар', 'Qatar', 634, 'QA', 'QAT', 'QA', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (638, 'РЕЮНЬОН', '', 'Reunion Island', 638, 'RE', 'REU', 'RE', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (642, 'РУМЫНИЯ', '', 'Romania', 642, 'RO', 'ROU', 'RO', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (643, 'РОССИЯ', 'Российская Федерация', 'Russia', 643, 'RU', 'RUS', 'RU', 'A');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (646, 'РУАНДА', 'Руандийская Республика', 'Rwanda', 646, 'RW', 'RWA', 'RW', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (652, 'СЕН-БАРТЕЛЕМИ', '', 'St. Barthelemy', 652, 'BL', 'BLM', 'NT', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (654, 'СВЯТАЯ ЕЛЕНА, ОСТРОВ ВОЗНЕСЕНИЯ, ТРИСТАН-ДА-КУНЬЯ', '', 'Saint Helena, Ascension and Tristan da Cunha', 654, 'SH', 'SHN', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (659, 'СЕНТ-КИТС И НЕВИС', '', 'St. Kitts and Nevis', 659, 'KN', 'KNA', 'KN', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (660, 'АНГИЛЬЯ', '', 'Anguilla', 660, 'AI', 'AIA', 'AI', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (662, 'СЕНТ-ЛЮСИЯ', '', 'St. Lucia', 662, 'LC', 'LCA', 'LC', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (663, 'СЕН-МАРТЕН', '', 'St. Martin', 663, 'MF', 'MAF', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (666, 'СЕН-ПЬЕР И МИКЕЛОН', '', 'Saint Pierre and Miquelon)', 666, 'PM', 'SPM', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (670, 'СЕНТ-ВИНСЕНТ И ГРЕНАДИНЫ', '', 'St. Vincent', 670, 'VC', 'VCT', 'VC', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (674, 'САН-МАРИНО', 'Республика Сан-Марино', 'San Marino', 674, 'SM', 'SMR', 'SM', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (678, 'САН-ТОМЕ И ПРИНСИПИ', 'Демократическая Республика Сан-Томе и Принсипи', 'Sao Tome and Principe', 678, 'ST', 'STP', 'ST', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (682, 'САУДОВСКАЯ АРАВИЯ', 'Королевство Саудовская Аравия', 'Saudi Arabia', 682, 'SA', 'SAU', 'SA', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (686, 'СЕНЕГАЛ', 'Республика Сенегал', 'Senegal', 686, 'SN', 'SEN', 'SN', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (688, 'СЕРБИЯ', 'Республика Сербия', 'Serbia', 688, 'RS', 'SRB', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (690, 'СЕЙШЕЛЫ', 'Республика Сейшелы', 'Seychelles', 690, 'SC', 'SYC', 'SC', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (694, 'СЬЕРРА-ЛЕОНЕ', 'Республика Сьерра-Леоне', 'Sierra Leone', 694, 'SL', 'SLE', 'SL', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (702, 'СИНГАПУР', 'Республика Сингапур', 'Singapore', 702, 'SG', 'SGP', 'SG', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (703, 'СЛОВАКИЯ', 'Словацкая Республика', 'Slovak Republic', 703, 'SK', 'SVK', 'SK', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (704, 'ВЬЕТНАМ', 'Социалистическая Республика Вьетнам', 'Vietnam', 704, 'VN', 'VNM', 'VN', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (705, 'СЛОВЕНИЯ', 'Республика Словения', 'Slovenia', 705, 'SI', 'SVN', 'SI', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (706, 'СОМАЛИ', 'Сомалийская Республика', 'Somalia', 706, 'SO', 'SOM', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (710, 'ЮЖНАЯ АФРИКА', 'Южно-Африканская Республика', 'South Africa', 710, 'ZA', 'ZAF', 'ZA', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (716, 'ЗИМБАБВЕ', 'Республика Зимбабве', 'Zimbabwe', 716, 'ZW', 'ZWE', 'ZW', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (724, 'ИСПАНИЯ', 'Королевство Испания', 'Spain', 724, 'ES', 'ESP', 'ES', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (732, 'ЗАПАДНАЯ САХАРА', '', 'Western Sahara', 732, 'EH', 'ESH', 'EH', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (736, 'СУДАН', 'Республика Судан', 'Sudan', 736, 'SD', 'SDN', 'SD', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (740, 'СУРИНАМ', 'Республика Суринам', 'Suriname', 740, 'SR', 'SUR', 'SR', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (744, 'ШПИЦБЕРГЕН И ЯН МАЙЕН', '', 'Svalbard and Jan Mayen', 744, 'SJ', 'SJM', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (748, 'СВАЗИЛЕНД', 'Королевство Свазиленд', 'Swaziland', 748, 'SZ', 'SWZ', 'SZ', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (752, 'ШВЕЦИЯ', 'Королевство Швеция', 'Sweden', 752, 'SE', 'SWE', 'SE', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (756, 'ШВЕЙЦАРИЯ', 'Швейцарская Конфедерация', 'Switzerland', 756, 'CH', 'CHE', 'CH', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (760, 'СИРИЙСКАЯ АРАБСКАЯ РЕСПУБЛИКА', '', 'Syria', 760, 'SY', 'SYR', 'SY', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (762, 'ТАДЖИКИСТАН', 'Республика Таджикистан', 'Tajikistan', 762, 'TJ', 'TJK', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (764, 'ТАИЛАНД', 'Королевство Таиланд', 'Thailand', 764, 'TH', 'THA', 'TH', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (768, 'ТОГО', 'Тоголезская Республика', 'Togo', 768, 'TG', 'TGO', 'TG', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (772, 'ТОКЕЛАУ', '', 'Tokelau', 772, 'TK', 'TKL', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (776, 'ТОНГА', 'Королевство Тонга', 'Tonga', 776, 'TO', 'TON', 'TO', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (780, 'ТРИНИДАД И ТОБАГО', 'Республика Тринидад и Тобаго', 'Trinidad and Tobago', 780, 'TT', 'TTO', 'TT', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (784, 'ОБЪЕДИНЕННЫЕ АРАБСКИЕ ЭМИРАТЫ', '', 'United Arab Emirates', 784, 'AE', 'ARE', 'AE', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (788, 'ТУНИС', 'Тунисская Республика', 'Tunisia', 788, 'TN', 'TUN', 'TN', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (792, 'ТУРЦИЯ', 'Турецкая Республика', 'Turkey', 792, 'TR', 'TUR', 'TR', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (795, 'ТУРКМЕНИЯ', 'Туркменистан', 'Turkmenistan, Republic of', 795, 'TM', 'TKM', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (796, 'ОСТРОВА ТЕРКС И КАЙКОС', '', 'Turks and Caicos Is.', 796, 'TC', 'TCA', 'TC', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (798, 'ТУВАЛУ', '', 'Tuvala', 798, 'TV', 'TUV', 'TV', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (800, 'УГАНДА', 'Республика Уганда', 'Uganda', 800, 'UG', 'UGA', 'UG', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (804, 'УКРАИНА', 'Республика Украина', 'Ukraine', 804, 'UA', 'UKR', 'UA', 'A');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (807, 'РЕСПУБЛИКА МАКЕДОНИЯ', '', 'Macedonia', 807, 'MK', 'MKD', 'MK', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (818, 'ЕГИПЕТ', 'Арабская Республика Египет', 'Egypt', 818, 'EG', 'EGY', 'EG', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (826, 'СОЕДИНЕННОЕ КОРОЛЕВСТВО', 'Соединенное Королевство Великобритании и Северной Ирландии', 'United Kingdom', 826, 'GB', 'GBR', 'GB', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (831, 'ГЕРНСИ', '', 'Guernsey', 831, 'GG', 'GGY', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (832, 'ДЖЕРСИ', '', 'Jersey', 832, 'JE', 'JEY', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (833, 'ОСТРОВ МЭН', '', 'The Isle of Man', 833, 'IM', 'IMN', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (834, 'ТАНЗАНИЯ, ОБЪЕДИНЕННАЯ РЕСПУБЛИКА', 'Объединенная Республика Танзания', 'Tanzania', 834, 'TZ', 'TZA', 'TZ', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (840, 'СОЕДИНЕННЫЕ ШТАТЫ', 'Соединенные Штаты Америки', 'U.S.A.', 840, 'US', 'USA', 'US', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (850, 'ВИРГИНСКИЕ ОСТРОВА, США', 'Виргинские острова Соединенных Штатов', 'U.S. Virgin Islands', 850, 'VI', 'VIR', 'VI', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (854, 'БУРКИНА-ФАСО', '', 'Burkino Faso', 854, 'BF', 'BFA', 'BF', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (858, 'УРУГВАЙ', 'Восточная Республика Уругвай', 'Uruguay', 858, 'UY', 'URY', 'UY', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (860, 'УЗБЕКИСТАН', 'Республика Узбекистан', 'Uzbekistan', 860, 'UZ', 'UZB', 'UZ', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (862, 'ВЕНЕСУЭЛА БОЛИВАРИАНСКАЯ РЕСПУБЛИКА', 'Боливарианская Республика Венесуэла', 'Venezuela', 862, 'VE', 'VEN', 'VE', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (876, 'УОЛЛИС И ФУТУНА', '', 'Wallis and Futuna Islands', 876, 'WF', 'WLF', 'WF', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (882, 'САМОА', 'Независимое Государство Самоа', 'Western Samoa', 882, 'WS', 'WSM', 'WS', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (887, 'ЙЕМЕН', 'Йеменская Республика', 'Yemen', 887, 'YE', 'YEM', 'YE', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (894, 'ЗАМБИЯ', 'Республика Замбия', 'Zambia', 894, 'ZM', 'ZMB', 'ZM', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (895, 'АБХАЗИЯ', 'Республика Абхазия', 'Abkhazia', 895, 'AB', 'ABH', '', 'A');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (896, 'ЮЖНАЯ ОСЕТИЯ', 'Республика Южная Осетия', 'South Ossetia', 896, 'OS', 'OST', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (4, 'АФГАНИСТАН', 'Переходное Исламское Государство Афганистан', 'Afghanistan', 4, 'AF', 'AFG', 'AF', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (8, 'АЛБАНИЯ', 'Республика Албания', 'Albania', 8, 'AL', 'ALB', 'AL', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (10, 'АНТАРКТИДА', '', 'Antarctica', 10, 'AQ', 'ATA', 'AQ', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (12, 'АЛЖИР', 'Алжирская Народная Демократическая Республика', 'Algeria', 12, 'DZ', 'DZA', 'DZ', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (16, 'АМЕРИКАНСКОЕ САМОА', '', 'American Samoa', 16, 'AS', 'ASM', 'AS', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (20, 'АНДОРРА', 'Княжество Андорра', 'Andorra', 20, 'AD', 'AND', 'AD', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (24, 'АНГОЛА', 'Республика Ангола', 'Angola', 24, 'AO', 'AGO', 'AO', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (28, 'АНТИГУА И БАРБУДА', '', 'Antigua', 28, 'AG', 'ATG', 'AG', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (31, 'АЗЕРБАЙДЖАН', 'Республика Азербайджан', 'Azerbaijan', 31, 'AZ', 'AZE', 'AZ', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (32, 'АРГЕНТИНА', 'Аргентинская Республика', 'Argentina', 32, 'AR', 'ARG', 'AR', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (36, 'АВСТРАЛИЯ', '', 'Australia', 36, 'AU', 'AUS', 'AU', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (40, 'АВСТРИЯ', 'Австрийская Республика', 'Austria', 40, 'AT', 'AUT', 'AT', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (44, 'БАГАМЫ', 'Содружество Багамы', 'Bahamas', 44, 'BS', 'BHS', 'BS', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (48, 'БАХРЕЙН', 'Королевство Бахрейн', 'Bahrain', 48, 'BH', 'BHR', 'BH', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (50, 'БАНГЛАДЕШ', 'Народная Республика Бангладеш', 'Bangladesh', 50, 'BD', 'BGD', 'BD', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (51, 'АРМЕНИЯ', 'Республика Армения', 'Armenia', 51, 'AM', 'ARM', 'AM', 'A');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (52, 'БАРБАДОС', '', 'Barbados', 52, 'BB', 'BRB', 'BB', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (56, 'БЕЛЬГИЯ', 'Королевство Бельгии', 'Belgium', 56, 'BE', 'BEL', 'BE', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (60, 'БЕРМУДЫ', '', 'Bermuda', 60, 'BM', 'BMU', 'BM', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (64, 'БУТАН', 'Королевство Бутан', 'Bhutan', 64, 'BT', 'BTN', 'BT', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (68, 'БОЛИВИЯ, МНОГОНАЦИОНАЛЬНОЕ ГОСУДАРСТВО', 'Многонациональное Государство Боливия', 'Bolivia', 68, 'BO', 'BOL', 'BO', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (70, 'БОСНИЯ И ГЕРЦЕГОВИНА', '', 'Bosnia and Herzegovina', 70, 'BA', 'BIH', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (72, 'БОТСВАНА', 'Республика Ботсвана', 'Botswana', 72, 'BW', 'BWA', 'BW', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (74, 'ОСТРОВ БУВЕ', '', 'Bouvet Island', 74, 'BV', 'BVT', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (76, 'БРАЗИЛИЯ', 'Федеративная Республика Бразилия', 'Brazil', 76, 'BR', 'BRA', 'BR', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (84, 'БЕЛИЗ', '', 'Belize', 84, 'BZ', 'BLZ', 'BZ', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (86, 'БРИТАНСКАЯ ТЕРРИТОРИЯ В ИНДИЙСКОМ ОКЕАНЕ', '', 'British Indian Ocean Territory', 86, 'IO', 'IOT', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (90, 'СОЛОМОНОВЫ ОСТРОВА', '', 'Solomon Islands', 90, 'SB', 'SLB', 'SB', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (92, 'ВИРГИНСКИЕ ОСТРОВА, БРИТАНСКИЕ', 'Британские Виргинские острова', 'British Virgin Is.', 92, 'VG', 'VGB', 'VG', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (96, 'БРУНЕЙ-ДАРУССАЛАМ', '', 'Brunei', 96, 'BN', 'BRN', 'BN', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (100, 'БОЛГАРИЯ', 'Республика Болгария', 'Bulgaria', 100, 'BG', 'BGR', 'BG', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (104, 'МЬЯНМА', 'Союз Мьянма', 'Myanmar', 104, 'MM', 'MMR', 'MM', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (108, 'БУРУНДИ', 'Республика Бурунди', 'Burundi', 108, 'BI', 'BDI', 'BI', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (112, 'БЕЛАРУСЬ', 'Республика Беларусь', 'Belarus ((Byelorussia)', 112, 'BY', 'BLR', 'BY', 'A');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (116, 'КАМБОДЖА', 'Королевство Камбоджа', 'Cambodia', 116, 'KH', 'KHM', 'KH', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (120, 'КАМЕРУН', 'Республика Камерун', 'Cameroon', 120, 'CM', 'CMR', 'CM', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (124, 'КАНАДА', '', 'Canada', 124, 'CA', 'CAN', 'CA', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (132, 'КАБО-ВЕРДЕ', 'Республика Кабо-Верде', 'Cape Verde', 132, 'CV', 'CPV', 'CV', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (136, 'ОСТРОВА КАЙМАН', '', 'Cayman Islands', 136, 'KY', 'CYM', 'KY', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (140, 'ЦЕНТРАЛЬНО-АФРИКАНСКАЯ РЕСПУБЛИКА', '', 'Central African', 140, 'CF', 'CAF', 'CF', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (144, 'ШРИ-ЛАНКА', 'Демократическая Социалистическая Республика Шри-Ланка', 'Sri Lanka', 144, 'LK', 'LKA', 'LK', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (148, 'ЧАД', 'Республика Чад', 'Chad', 148, 'TD', 'TCD', 'TD', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (152, 'ЧИЛИ', 'Республика Чили', 'Chile', 152, 'CL', 'CHL', 'CL', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (156, 'КИТАЙ', 'Китайская Народная Республика', 'China', 156, 'CN', 'CHN', 'CN', 'A');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (158, 'ТАЙВАНЬ (КИТАЙ)', '', 'Taiwan', 158, 'TW', 'TWN', 'TW', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (162, 'ОСТРОВ РОЖДЕСТВА', '', 'Christmas Island', 162, 'CX', 'CXR', 'CX', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (166, 'КОКОСОВЫЕ (КИЛИНГ) ОСТРОВА', '', 'Cocos Islands', 166, 'CC', 'CCK', 'CC', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (170, 'КОЛУМБИЯ', 'Республика Колумбия', 'Colombia', 170, 'CO', 'COL', 'CO', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (174, 'КОМОРЫ', 'Союз Коморы', 'Comoro islands', 174, 'KM', 'COM', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (175, 'МАЙОТТА', '', 'МАЙОТТА', 175, 'YT', 'MYT', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (180, 'КОНГО, ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА', 'Демократическая Республика Конго', 'Congo, The Republic of', 180, 'CD', 'COD', 'CD', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (184, 'ОСТРОВА КУКА', '', 'Cook Islands', 184, 'CK', 'COK', 'CK', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (188, 'КОСТА-РИКА', 'Республика Коста-Рика', 'Costa Rica', 188, 'CR', 'CRI', 'CR', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (191, 'ХОРВАТИЯ', 'Республика Хорватия', 'Croatia', 191, 'HR', 'HRV', 'HR', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (192, 'КУБА', 'Республика Куба', 'Cuba', 192, 'CU', 'CUB', 'CU', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (196, 'КИПР', 'Республика Кипр', 'Cyprus', 196, 'CY', 'CYP', 'CY', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (203, 'ЧЕШСКАЯ РЕСПУБЛИКА', '', 'Czech Republic', 203, 'CZ', 'CZE', 'CZ', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (204, 'БЕНИН', 'Республика Бенин', 'Benin', 204, 'BJ', 'BEN', 'BJ', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (208, 'ДАНИЯ', 'Королевство Дания', 'Denmark', 208, 'DK', 'DNK', 'DK', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (212, 'ДОМИНИКА', 'Содружество Доминики', 'Dominica', 212, 'DM', 'DMA', 'DM', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (214, 'ДОМИНИКАНСКАЯ РЕСПУБЛИКА', '', 'Dominican Republic', 214, 'DO', 'DOM', 'DO', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (218, 'ЭКВАДОР', 'Республика Эквадор', 'Ecuador', 218, 'EC', 'ECU', 'EC', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (222, 'ЭЛЬ-САЛЬВАДОР', 'Республика Эль-Сальвадор', 'El Salvador', 222, 'SV', 'SLV', 'SV', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (226, 'ЭКВАТОРИАЛЬНАЯ ГВИНЕЯ', 'Республика Экваториальная Гвинея', 'Equatorial Guinea', 226, 'GQ', 'GNQ', 'GQ', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (231, 'ЭФИОПИЯ', 'Федеративная Демократическая Республика Эфиопия', 'Ethiopia', 231, 'ET', 'ETH', 'ET', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (232, 'ЭРИТРЕЯ', '', 'Eritrea', 232, 'ER', 'ERI', 'ER', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (233, 'ЭСТОНИЯ', 'Эстонская Республика', 'Estonia', 233, 'EE', 'EST', 'EE', 'A');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (234, 'ФАРЕРСКИЕ ОСТРОВА', '', 'Faeroe Islands', 234, 'FO', 'FRO', 'FO', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (238, 'ФОЛКЛЕНДСКИЕ ОСТРОВА (МАЛЬВИНСКИЕ)', '', 'Falkland Islands (Malvinas)', 238, 'FK', 'FLK', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (239, 'ЮЖНАЯ ДЖОРДЖИЯ И ЮЖНЫЕ САНДВИЧЕВЫ ОСТРОВА', '', 'South Georgia And The South Sandwich Islands.', 239, 'GS', 'SGS', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (242, 'ФИДЖИ', 'Республика Островов Фиджи', 'Fiji', 242, 'FJ', 'FJI', 'FJ', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (246, 'ФИНЛЯНДИЯ', 'Финляндская Республика', 'Finland', 246, 'FI', 'FIN', 'FI', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (248, 'ЭЛАНДСКИЕ ОСТРОВА', '', 'Aland Islands', 248, 'AX', 'ALA', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (250, 'ФРАНЦИЯ', 'Французская Республика', 'France', 250, 'FR', 'FRA', 'FR', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (254, 'ФРАНЦУЗСКАЯ ГВИАНА', '', 'French Guiana', 254, 'GF', 'GUF', 'GF', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (258, 'ФРАНЦУЗСКАЯ ПОЛИНЕЗИЯ', '', 'French Polynesia', 258, 'PF', 'PYF', 'PF', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (260, 'ФРАНЦУЗСКИЕ ЮЖНЫЕ ТЕРРИТОРИИ', '', 'Presentation of French Austral and Antarctic Territories', 260, 'TF', 'ATF', '', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (262, 'ДЖИБУТИ', 'Республика Джибути', 'Djibouti', 262, 'DJ', 'DJI', 'DJ', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (266, 'ГАБОН', 'Габонская Республика', 'Gabon', 266, 'GA', 'GAB', 'GA', 'H');
INSERT INTO public.countries (id, short_name, long_name, short_eng_name, oksm, code2, code3, iata, status) VALUES (178, 'КОНГО', 'Республика Конго', 'Congo', 178, 'CG', 'COG', 'CG', 'A');
